sudo: false
dist: focal
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
# There is no Windows support on travis for now, so no pypiwin32 required
install:
    - "pip install sphinx tabulate"

# commands to run tests (we "cd" to ensure that we don't import the wrong rsfile package)
script:
    - "python setup.py install"
    - "cd doc"
    - "python -m  rsfile.rstest.test_rsfile_streams"
    - "python -m  rsfile.rstest.test_rsfile_locking"
    - "python -m  rsfile.rstest.test_rsfile_retrocompatibility"
    - "python -m  rsfile.rstest.test_rsfile_stdlib"
    - 'sphinx-build -W -b html -d "{envtmpdir}/doctrees" .  "{envtmpdir}/html"'
